import type { NextPage } from "next";
import Head from "next/head";
import { Loader } from "../components/Loader";

const Home: NextPage = () => {
  return (
    <div className="container px-6 py-4">
      <Head>
        <title>Next Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
